name: Welcome Contributors

on:
  fork:
  push:
    branches: [develop]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send Welcome Message
        uses: EddieHubCommunity/gh-action-community@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Feeling great to have your contribution for this project</h1> Welcome to our project'
          pr-message: '<h1>Feeling great to have your contribution for this project</h1> Welcome to our project'
          footer: 'Our developers will respond to you as soon as possible. Any questions? Let us know.'
